# Generated by Django 2.1.2 on 2018-11-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('generic_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('doz', models.CharField(max_length=15, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name', 'created'),
            },
        ),
        migrations.CreateModel(
            name='MedmeUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.TextField(default='')),
                ('status', models.TextField(default='not confirmed')),
                ('productCharges', models.IntegerField(default=0)),
                ('deliveryCharges', models.IntegerField(default=0)),
                ('extraCharges', models.IntegerField(default=0)),
                ('totalBill', models.IntegerField(default=0)),
                ('paymentReceived', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='medme.MedmeUser')),
                ('items', models.ManyToManyField(blank=True, to='medme.Medicine')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
