# Generated by Django 2.1.2 on 2018-11-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medmeuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='not confirmed', max_length=20),
        ),
    ]
