# Generated by Django 2.1.2 on 2018-11-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medme', '0002_auto_20181102_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT_CONFIRMED', 'Not Confirmed'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='NOT_CONFIRMED', max_length=20),
        ),
    ]
