# Generated by Django 2.1.2 on 2018-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medme', '0003_auto_20181102_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='medme.Medicine'),
        ),
    ]
