# Generated by Django 2.1.2 on 2018-11-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='composition',
        ),
        migrations.AddField(
            model_name='composition',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medme.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drugs',
            field=models.ManyToManyField(related_name='drugs', through='medme.Composition', to='medme.Drug'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medme.Drug'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
